### ISSUE TITLE
[address bug]Some Heap-Buffer-Overflow crashes with asan in binary idlc

### ISSUE THREAD

**Issue by Yhcrown** [eclipse-cyclonedds/cyclonedds#1368]
**Hi, developers of cyclonedds:**
Recently, I tested the binary idlc instrumented with ASAN by our fuzzing tool. It incurred some crashes with the following error information. 
I found three heap-buffer-overflow bug with different execution stack:

For crash input:
https://github.com/Yhcrown/fuzzing-crashes/blob/main/validated/idlc-new/0
error output:
```
=================================================================
==46256==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6310000007ff at pc 0x563bd10ef878 bp 0x7fff20ec4c00 sp 0x7fff20ec4bf8
READ of size 1 at 0x6310000007ff thread T0
    #0 0x563bd10ef877 in get_line /workspace/test/cyclonedds/src/tools/idlpp/src/support.c:1960:13
    #1 0x563bd10e9e89 in parse_line /workspace/test/cyclonedds/src/tools/idlpp/src/support.c:1653:15
    #2 0x563bd10e6c6a in get_ch /workspace/test/cyclonedds/src/tools/idlpp/src/support.c:1580:13
    #3 0x563bd10de4a9 in mcpp_main /workspace/test/cyclonedds/src/tools/idlpp/src/main.c:637:17
    #4 0x563bd10de4a9 in mcpp_lib_main /workspace/test/cyclonedds/src/tools/idlpp/src/main.c:430:5
    #5 0x563bd10b9579 in idlc_parse /workspace/test/cyclonedds/src/tools/idlc/src/idlc.c:331:9
    #6 0x563bd10b8c84 in main /workspace/test/cyclonedds/src/tools/idlc/src/idlc.c:703:16
    #7 0x7f94631d3d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)
    #8 0x7f94631d3e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)
    #9 0x563bd0ffa8e4 in _start (/workspace/test/cyclonedds/bin/idlc+0x438e4) (BuildId: e526cf43a1a1020257bfd1c9437645cac70cf01e)

0x6310000007ff is located 1 bytes to the left of 65536-byte region [0x631000000800,0x631000010800)
allocated by thread T0 here:
    #0 0x563bd107d72e in __interceptor_malloc (/workspace/test/cyclonedds/bin/idlc+0xc672e) (BuildId: e526cf43a1a1020257bfd1c9437645cac70cf01e)
    #1 0x563bd10ebe9e in xmalloc /workspace/test/cyclonedds/src/tools/idlpp/src/support.c:2341:28
    #2 0x563bd10ebe9e in get_file /workspace/test/cyclonedds/src/tools/idlpp/src/support.c:2287:20

SUMMARY: AddressSanitizer: heap-buffer-overflow /workspace/test/cyclonedds/src/tools/idlpp/src/support.c:1960:13 in get_line
Shadow bytes around the buggy address:
  0x0c627fff80a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c627fff80b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c627fff80c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c627fff80d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c627fff80e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c627fff80f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa[fa]
  0x0c627fff8100: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c627fff8110: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c627fff8120: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c627fff8130: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c627fff8140: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==46256==ABORTING
```

For crash input:
https://github.com/Yhcrown/fuzzing-crashes/blob/main/validated/idlc/2
error output:
```
==51928==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6030000011f2 at pc 0x563146ddecde bp 0x7ffea7d356d0 sp 0x7ffea7d356c8
WRITE of size 1 at 0x6030000011f2 thread T0
    #0 0x563146ddecdd in do_msg /workspace/test/cyclonedds/src/tools/idlpp/src/support.c:2522:23
    #1 0x563146dd9349 in scan_quote /workspace/test/cyclonedds/src/tools/idlpp/src/support.c
    #2 0x563146ddb1c5 in parse_line /workspace/test/cyclonedds/src/tools/idlpp/src/support.c:1757:22
    #3 0x563146dd7c6a in get_ch /workspace/test/cyclonedds/src/tools/idlpp/src/support.c:1580:13
    #4 0x563146dcf4a9 in mcpp_main /workspace/test/cyclonedds/src/tools/idlpp/src/main.c:637:17
    #5 0x563146dcf4a9 in mcpp_lib_main /workspace/test/cyclonedds/src/tools/idlpp/src/main.c:430:5
    #6 0x563146daa579 in idlc_parse /workspace/test/cyclonedds/src/tools/idlc/src/idlc.c:331:9
    #7 0x563146da9c84 in main /workspace/test/cyclonedds/src/tools/idlc/src/idlc.c:703:16
    #8 0x7f52e36e8d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)
    #9 0x7f52e36e8e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)
    #10 0x563146ceb8e4 in _start (/workspace/test/cyclonedds/bin/idlc+0x438e4) (BuildId: e526cf43a1a1020257bfd1c9437645cac70cf01e)

0x6030000011f2 is located 0 bytes to the right of 18-byte region [0x6030000011e0,0x6030000011f2)
allocated by thread T0 here:
    #0 0x563146d6e72e in __interceptor_malloc (/workspace/test/cyclonedds/bin/idlc+0xc672e) (BuildId: e526cf43a1a1020257bfd1c9437645cac70cf01e)
    #1 0x563146ddd785 in do_msg /workspace/test/cyclonedds/src/tools/idlpp/src/support.c:2465:35
    #2 0x563146dd9349 in scan_quote /workspace/test/cyclonedds/src/tools/idlpp/src/support.c
    #3 0x563146ddb1c5 in parse_line /workspace/test/cyclonedds/src/tools/idlpp/src/support.c:1757:22

SUMMARY: AddressSanitizer: heap-buffer-overflow /workspace/test/cyclonedds/src/tools/idlpp/src/support.c:2522:23 in do_msg
Shadow bytes around the buggy address:
  0x0c067fff81e0: fa fa fd fd fd fa fa fa fd fd fd fd fa fa fd fd
  0x0c067fff81f0: fd fa fa fa fd fd fd fa fa fa fd fd fd fd fa fa
  0x0c067fff8200: fd fd fd fa fa fa fd fd fd fd fa fa fd fd fd fd
  0x0c067fff8210: fa fa fd fd fd fd fa fa fd fd fd fd fa fa fd fd
  0x0c067fff8220: fd fd fa fa fd fd fd fd fa fa fd fd fd fd fa fa
=>0x0c067fff8230: fd fd fd fd fa fa fd fd fd fd fa fa 00 00[02]fa
  0x0c067fff8240: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff8250: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff8260: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff8270: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff8280: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==51928==ABORTING
```

For crash input:
https://github.com/Yhcrown/fuzzing-crashes/blob/main/validated/idlc/7
error output:
```
=================================================================
==65932==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6310000787ff at pc 0x561a61a8d8c5 bp 0x7ffcc5972660 sp 0x7ffcc5972658
READ of size 1 at 0x6310000787ff thread T0
    #0 0x561a61a8d8c4 in parse_line /workspace/test/cyclonedds/src/tools/idlpp/src/support.c:1747:38
    #1 0x561a61a88c6a in get_ch /workspace/test/cyclonedds/src/tools/idlpp/src/support.c:1580:13
    #2 0x561a61a81117 in mcpp_main /workspace/test/cyclonedds/src/tools/idlpp/src/main.c:637:17
    #3 0x561a61a81117 in mcpp_lib_main /workspace/test/cyclonedds/src/tools/idlpp/src/main.c:430:5
    #4 0x561a61a5b579 in idlc_parse /workspace/test/cyclonedds/src/tools/idlc/src/idlc.c:331:9
    #5 0x561a61a5ac84 in main /workspace/test/cyclonedds/src/tools/idlc/src/idlc.c:703:16
    #6 0x7f0f16fb5d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)
    #7 0x7f0f16fb5e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)
    #8 0x561a6199c8e4 in _start (/workspace/test/cyclonedds/bin/idlc+0x438e4) (BuildId: e526cf43a1a1020257bfd1c9437645cac70cf01e)

0x6310000787ff is located 1 bytes to the left of 65536-byte region [0x631000078800,0x631000088800)
allocated by thread T0 here:
    #0 0x561a61a1f72e in __interceptor_malloc (/workspace/test/cyclonedds/bin/idlc+0xc672e) (BuildId: e526cf43a1a1020257bfd1c9437645cac70cf01e)
    #1 0x561a61a8bfbf in xmalloc /workspace/test/cyclonedds/src/tools/idlpp/src/support.c:2341:28
    #2 0x561a61a8bfbf in parse_line /workspace/test/cyclonedds/src/tools/idlpp/src/support.c:1662:17

SUMMARY: AddressSanitizer: heap-buffer-overflow /workspace/test/cyclonedds/src/tools/idlpp/src/support.c:1747:38 in parse_line
Shadow bytes around the buggy address:
  0x0c62800070a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c62800070b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c62800070c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c62800070d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c62800070e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c62800070f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa[fa]
  0x0c6280007100: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c6280007110: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c6280007120: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c6280007130: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c6280007140: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==65932==ABORTING
```

### Verification steps：

```
git clone https://github.com/eclipse-cyclonedds/cyclonedds
cd cyclonedd
mkdir check_build && cd check_build
cmake ../ -DCMAKE_C_COMPILER=clang  -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_FLAGS="-fsanitize=address -U_FORTIFY_SOURCE" -DCMAKE_CXX_FLAGS="-fsanitize=address -U_FORTIFY_SOURCE"
cmake --build .
cd bin
./idlc ./crash_input
```

### enviroment:
Ubuntu 22.04 LTS
Linux lab-pro 4.15.0-147-generic
gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Ubuntu clang version 14.0.6

Any help would be greatly appreciated from you :D
**Thanks & Best regards !**

**Comment by dpotman** [comment]
> After my verification, https://github.com/Yhcrown/fuzzing-crashes/blob/main/validated/idlc/7 still report an error

Sorry, I missed that (in my debug build this input resulted in an assertion, which was a bit hidden in all the messy warning and error output from the preprocessor). I'll look into this again.

**Comment by dpotman** [comment]
The changes in #1384 should fix the error triggered by input `7`.
