### ISSUE TITLE
Memory leak detected in idlc with Asan

### ISSUE THREAD

**Issue by fadi-labib** [eclipse-cyclonedds/cyclonedds#799]
From @sumanth-nirmal 

I have compiled `cyclonedds` and `cyclonedds-cxx` with Address sanitizer, while compiling the generated code the following memory leaks are detected:

```sh
=================================================================
==20395==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 154 byte(s) in 1 object(s) allocated from:
    #0 0x7f0c30b9bb40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x55fc0b0eeb8d in xmalloc /home/sumanth.nirmal/cyclone_ws/cyclonedds/src/tools/idlpp/src/support.c:2342
    #2 0x55fc0b0f7b4d in norm_path /home/sumanth.nirmal/cyclone_ws/cyclonedds/src/tools/idlpp/src/system.c:2593
    #3 0x55fc0b0fa8d7 in open_file /home/sumanth.nirmal/cyclone_ws/cyclonedds/src/tools/idlpp/src/system.c:3506
    #4 0x55fc0b0fa50b in search_dir /home/sumanth.nirmal/cyclone_ws/cyclonedds/src/tools/idlpp/src/system.c:3437
    #5 0x55fc0b0fa291 in open_include /home/sumanth.nirmal/cyclone_ws/cyclonedds/src/tools/idlpp/src/system.c:3343
    #6 0x55fc0b0f9c6f in do_include /home/sumanth.nirmal/cyclone_ws/cyclonedds/src/tools/idlpp/src/system.c:3240
    #7 0x55fc0b100fb8 in directive /home/sumanth.nirmal/cyclone_ws/cyclonedds/src/tools/idlpp/src/directive.c:325
    #8 0x55fc0b0dccb4 in mcpp_main /home/sumanth.nirmal/cyclone_ws/cyclonedds/src/tools/idlpp/src/main.c:645
    #9 0x55fc0b0dc4cb in mcpp_lib_main /home/sumanth.nirmal/cyclone_ws/cyclonedds/src/tools/idlpp/src/main.c:430
    #10 0x55fc0b0da482 in idlc_parse /home/sumanth.nirmal/cyclone_ws/cyclonedds/src/tools/idlc/idlc.c:231
    #11 0x55fc0b0db2df in main /home/sumanth.nirmal/cyclone_ws/cyclonedds/src/tools/idlc/idlc.c:436
    #12 0x7f0c3028fb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

Direct leak of 70 byte(s) in 1 object(s) allocated from:
    #0 0x7f0c30b9bb40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x55fc0b0eeb8d in xmalloc /home/sumanth.nirmal/cyclone_ws/cyclonedds/src/tools/idlpp/src/support.c:2342
    #2 0x55fc0b0ee536 in save_string /home/sumanth.nirmal/cyclone_ws/cyclonedds/src/tools/idlpp/src/support.c:2268
    #3 0x55fc0b0f9a69 in do_include /home/sumanth.nirmal/cyclone_ws/cyclonedds/src/tools/idlpp/src/system.c:3212
    #4 0x55fc0b100fb8 in directive /home/sumanth.nirmal/cyclone_ws/cyclonedds/src/tools/idlpp/src/directive.c:325
    #5 0x55fc0b0dccb4 in mcpp_main /home/sumanth.nirmal/cyclone_ws/cyclonedds/src/tools/idlpp/src/main.c:645
    #6 0x55fc0b0dc4cb in mcpp_lib_main /home/sumanth.nirmal/cyclone_ws/cyclonedds/src/tools/idlpp/src/main.c:430
    #7 0x55fc0b0da482 in idlc_parse /home/sumanth.nirmal/cyclone_ws/cyclonedds/src/tools/idlc/idlc.c:231
    #8 0x55fc0b0db2df in main /home/sumanth.nirmal/cyclone_ws/cyclonedds/src/tools/idlc/idlc.c:436
    #9 0x7f0c3028fb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

SUMMARY: AddressSanitizer: 224 byte(s) leaked in 2 allocation(s).
```

**Comment by fadi-labib** [comment]
From @k0ekk0ek 

mcpp has it's quirks. I've noticed some myself and there's a couple of forks out there that have extra patches that'll be included at some point. It's just that I have to go through the Eclipse IP review process to get them in. Also, it's not a big of a deal because it's only in the compiler, not libidl, which can be used as a base library for higher-level languages and such. I'll leave this open for now, but I expect it'll magically get solved once the extra patches are in.

**Comment by k0ekk0ek** [comment]
This particular issue pops up if a file is included in case anyone wants to reproduce. For completeness, this is very likely solved in one of the other forks of mcpp. Once 0.8 is shipped I'll issue a CQ to include 3rd party patches.
